puts " My Home "
puts ""
puts "       /\\  "
puts "      /  \\  "
puts "     /    \\  "
puts "    /      \\  "
puts "   /        \\  "
puts "  /          \\ "
puts " +------------+ "
puts " |            | "
puts " |            | "
puts " |   +---+    | "
puts " |   |   |    | "
puts " |   |   |    | "
puts " +---+---+----+ "
puts ""